# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
name: Build
on:
  push:
    branches:
      - !master
jobs:
  ANDROID_BASE_CHECKS:
    name: Base Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Perform base checks
        run: ./gradlew assembleDebug build
  ANDROID_UNIT_TESTS:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Execute unit tests
        run: ./gradlew build testDebugUnitTest
      - name: Upload UnitTest Coverage
        uses: actions/upload-artifact@v1
        with:
          name: unit_tests
          path: app/build/jacoco/
  ANDROID_EMULATOR_TESTS:
    name: Emulator Tests
    runs-on: macOS-latest
    strategy:
      matrix:
        EMULATOR_API: [26]
        EMULATOR_ARCH: [x86_64]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Execute emulator tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.EMULATOR_API }}
          arch: ${{ matrix.EMULATOR_ARCH }}
          disable-animations: true
          headless: true
          script: ./gradlew build connectedCheck createDebugCoverageReport
      - name: Upload ConnectedTest Coverage
        uses: actions/upload-artifact@v1
        with:
          name: emulator_tests
          path: app/build/outputs/code_coverage/debugAndroidTest/connected
  CODE_COVERAGE:
    name: Code Coverage Report
    runs-on: ubuntu-latest
    needs: [ANDROID_UNIT_TESTS, ANDROID_EMULATOR_TESTS]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Download ConnectedTest Coverage
        uses: actions/download-artifact@v1
        with:
          name: emulator_tests
          path: app/build/outputs/code_coverage/debugAndroidTest/connected
      - name: Download UnitTest Coverage
        uses: actions/download-artifact@v1
        with:
          name: unit_tests
          path: app/build/jacoco/
      - name: Compile & Publish Code Coverage
        uses: paambaati/codeclimate-action@v2.5.6
        env:
          CC_TEST_REPORTER_ID: "a1ff1923b1a21d1931dd37f5869568344bc02d22eb89cab785be5b1f851466ed"
          JACOCO_SOURCE_PATH: "app/src/main/java/"
        with:
          coverageCommand: ./gradlew build jacocoTestReport
          coverageLocations: "app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml:jacoco"
      - name: Upload Jacoco Coverage
        uses: actions/upload-artifact@v1
        with:
          name: jacoco_tests
          path: app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
